# Generated by Django 3.2.3 on 2021-05-28 03:56

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')])),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')])),
                ('subject', models.CharField(max_length=200)),
                ('message', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('prof', models.CharField(max_length=20, verbose_name='Profession')),
                ('img', models.ImageField(upload_to='media', verbose_name='Profile Picture')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='About Me')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, verbose_name='Icon')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('dics', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
