# Generated by Django 3.2.3 on 2021-05-29 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('prop_img', models.ImageField(upload_to='realestate/testimonial', verbose_name='Project Image')),
                ('img', models.ImageField(upload_to='realestate/testimonial', verbose_name='Image')),
                ('prof', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('disc', models.CharField(max_length=500, verbose_name='Review')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
        migrations.AddField(
            model_name='address',
            name='location_line_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='location_line_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Address Line 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='location_line_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 3'),
        ),
    ]
