# Generated by Django 3.2.3 on 2021-05-29 05:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210529_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='img',
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number'),
        ),
    ]
